DROP TABLE IF EXISTS items;
DROP TABLE IF EXISTS users;

CREATE TABLE users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  email VARCHAR(255) NOT NULL,
  name VARCHAR(255),
  CONSTRAINT pk_user PRIMARY KEY (id),
  CONSTRAINT uq_user_email UNIQUE (email)
);

CREATE TABLE items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  user_id BIGINT,
  url VARCHAR(1000),
  resolved_url VARCHAR(1000),
  mime_type VARCHAR(255),
  title VARCHAR(1000),
  has_image BOOLEAN,
  has_video BOOLEAN,
  date_resolved DATE,
  CONSTRAINT pk_item PRIMARY KEY (id),
  CONSTRAINT fk_item_user FOREIGN KEY (user_id) REFERENCES users (id)
);